### ISSUE TITLE
About  the krahenbuhl2013 module

### ISSUE THREAD

**Issue by Maoys1997** [yaoqi-zd/SGAN#1]
Hi, @yaoqi-zd , I'm studying your paper and trying to reproduce your result. However, I met a problem using the krahenbuhl2013 that I never met before. Can you give me the source code if it be convenient to you. Thanks.

**Comment by yaoqi-zd** [comment]
@Maoys1997 Hi, to use krahenbuhl2013, please refer  https://github.com/kolesman/SEC to install the CRF module.
