### ISSUE TITLE
Low experimental results

### ISSUE THREAD

**Issue by GX77** [yaoqi-zd/SGAN#13]
Hello, I follow your steps to train, generate seeds and verify seed quality.But the final mIoU was only 49.37%, MP was only 76.40% and MR Was only 57.11%.Can I fix it in any way?

**Comment by yaoqi-zd** [comment]
@GX77 Hi, you have reproduced the seeds with exactly the same quality. In README, we have claimed: 

'If you have finished all the steps above, you will get the seeds with precision=76.38 recall=57.26. The result is slightly different with that reported in our paper(precision=76.37, recall=57.35)'

so your generated seeds look fine, and you can use them to train a segmentation model.

**Comment by GX77** [comment]
Oh, I mistook the segmentation index in the paper for the quality index of the seed.Thank you very much.
