### ISSUE TITLE
For the segmentation part

### ISSUE THREAD

**Issue by GX77** [yaoqi-zd/SGAN#14]
Excuse me, I'm troubled by some problems.
After obtaining the seed, why continue to complete the segmentation in DSRG?As described in the paper, should not the segmentation be completed in the ResNet-101 network or VGG-16 network?

**Comment by yaoqi-zd** [comment]
@GX77 the seeds are used as pseudo-label to train segmentation network, such as FCN or Deeplab, in our paper, we train a deeplabv2 network and adopt the balanced seed loss introduced in DSRG. VGG-16 and ResNet-101 are backbones.

**Comment by GX77** [comment]
Thank you very much. I see what you mean.But where can I get the complete code?I am new to deep learning and want to run SGAN network framework completely.

**Comment by yaoqi-zd** [comment]
@GX77 I'm afraid the dsrg training part is a little complicated for you if you are new to DL. you can refer to issue #8 for more details, or you can refer to official [dsrg repo](https://github.com/speedinghzl/DSRG/) if you want.

**Comment by GX77** [comment]
Well, I'll think about it.Thank you.
