### ISSUE TITLE
ResNet Backbone

### ISSUE THREAD

**Issue by SharhadBashar** [yaoqi-zd/SGAN#16]
Where can i find the code for the resnet backbone?

**Comment by yaoqi-zd** [comment]
@SharhadBashar Hi, we only use vgg16 as backbone in SGAN model, when training the segmentation network, we tried vgg16 and resnet101.

**Comment by SharhadBashar** [comment]
So if I want to reproduce the results you have in table 1, under Backbone: ResNet network how would I set up the code?

**Comment by yaoqi-zd** [comment]
@SharhadBashar you can use the pseudo label generated by our SGAN to train a resnet-101 segmentation model. you can refer DSRG repo to find the resnet-based prototxt
