### ISSUE TITLE
关于训练文件deeplabv2_weakly.prototxt

### ISSUE THREAD

**Issue by zmll** [yaoqi-zd/SGAN#3]
谢谢你分享的代码，受益匪浅；但是，我在复现训练过程时发现deeplabv2_weakly.prototxt只包含了图像的种子部分，并没有训练图像？那怎么实现DSRG分割的训练？期待你的回复！

**Comment by yaoqi-zd** [comment]
@zmll 你好，deeplabv2_weakly.prototxt使用的数据层是ImageSegData（来自deeplab官方repo），DSRG使用的数据层是ImageData。

为了使用ImageSegData层，你可以参考deeplab的做法，需要提供一个list，里面每一行表示一个训练样本，每一行包括两部分：image_path + seed(seg label) path。

同时我们和deeplab中使用的ImageSegData的不同之处在于，我们修改了ImageSegData层的源码，增加了color distortion，如果你直接使用deeplab官方的caffe的话，需要把我们提供的deeplab_weakly.prototxt里面的distort_param注释掉。增加distortion可以略微提高分割性能。

**Comment by zmll** [comment]
@yaoqi-zd 明白了，十分感谢你的帮助！

**Comment by zmll** [comment]
@yaoqi-zd 很抱歉再次打扰您，对比了deeplab_weakly.prototxt与DSRG中的prototxt文件，发现您的文件中去掉了DSRGLayer的内容，是表明您的项目没有再使用“种子区域生长”的方法吗？直接应用高质量的seed进行分割训练？
还有，在运行中出现pylayers 中没有“Label2Seed”的问题，方便的话，能不能提供一份新的pylayers文件呢？万分感谢！

**Comment by yaoqi-zd** [comment]
- 通过SGAN得到种子点之后，不需要再进行种子点区域生长。因此可以不用DSRGLayer;

- Label2Seed就是将[h, w]形状的segmentation label转换成[h, w, c]的seed，其中c表示所有类别，包括背景。生成的过程其实就是对label图上[ph, pw]，值为k的点，将seed上[ph, pw, k]位置置1。

**Comment by zmll** [comment]
pylayer文件中，除了增加Label2Seed部分代码以外，您还修改其他层了吗？

**Comment by yaoqi-zd** [comment]
@zmll 印象里没有。其实得到种子点之后，用种子点训练分割网络这一步大多数论文都差不多，网络结构基本都是deeplabv2，训练的loss看情况，有的用balanced seed loss(DSRG提出的)，有的用cross entropy loss，同时绝大多数还额外加了CRF loss约束预测结果。剩下分割网络训练中的细节对最终分割性能的影响都不是关键的。
