### ISSUE TITLE
Is file of im_transforms.hpp lost?

### ISSUE THREAD

**Issue by ucmmesa** [yaoqi-zd/SGAN#5]
Thanks for your nice share!
When I tried to make the caffe under the dsrg directory,I got the following error prompt:
src/caffe/data_transformer.cpp:10:40: fatal error: caffe/util/im_transforms.hpp: No such file or directory.
I am not sure where to find the  im_transforms.hpp.Can you please give me any advices?

**Comment by yaoqi-zd** [comment]
@ucmmesa I'll check after work today, please wait for some hours.

**Comment by yaoqi-zd** [comment]
@ucmmesa hi, I update the caffe directory and you can clone the latest code to test

**Comment by ucmmesa** [comment]
@yaoqi-zd hi,the dsrg part training is ok now.Thanks very much.
