### ISSUE TITLE
about segmentation result usage

### ISSUE THREAD

**Issue by ucmmesa** [yaoqi-zd/SGAN#6]
After training the SGAN,the 8000 times iteration training model could be gotton and the segmentated seeds are stored under the directory like sgan_vgg16_321x321_snet_seedcam.But,when traing under the dsrg directory,the seeds in the list asked for the directory like sgan_vgg16_321x321_sdnet_seedseg.Do these two directories mean the same thing?

**Comment by yaoqi-zd** [comment]
@ucmmesa yes, in fact, the list(e.g. `seed_sdnet_seedseg.txt`) tells the `ImageSegData` layer the image path and seed path for each training samples. so you need to modify the list file to let it point to your own image and seed path.
