### ISSUE TITLE
About the dsrg training part

### ISSUE THREAD

**Issue by lianxxx** [yaoqi-zd/SGAN#8]
Sorry, I don't know about caffe and may ask some silly questions. I installed caffe2 and set the python path, and ran the run_anti_noise.sh and got following error:

I0502 10:50:02.235517 13834 solver.cpp:77] Creating training net from train_net file: config/deeplabv2_weakly.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 17:19: Message type "caffe.TransformationParameter" has no field named "distort_param".
Also no field named "ignore_label". 

Could you please help with this problem. Thank you.

**Comment by yaoqi-zd** [comment]
@lianxxx Hi, I have no experience of caffe2. to train the dsrg model, you can refer to [DSRG](https://github.com/speedinghzl/DSRG) repo or [deeplabv2](https://bitbucket.org/aquariusjay/deeplab-public-ver2/src) for detailed installation and runing guides. Basically it follows the below steps:
1. download caffe src and compile(caffe bin and python port);
2. for dsrg, modify the `python path` in `findcaffe.py` to caffe python directory;
3. for dsrg, modify the list file to point to image path and seed path, please refer to issue #6 
4. in termial, run `run_anti_noise.sh` to train/validate/test
